//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinApt.Client {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WinAptStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WinAptStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinApt.Client.WinAptStrings", typeof(WinAptStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chose base folder to save files:.
        /// </summary>
        internal static string strChoseFormOpenFile {
            get {
                return ResourceManager.GetString("strChoseFormOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently there is no such DB file, update DB now?.
        /// </summary>
        internal static string strConfigFormDownload {
            get {
                return ResourceManager.GetString("strConfigFormDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need Update DB.
        /// </summary>
        internal static string strConfigFormMessageTitle {
            get {
                return ResourceManager.GetString("strConfigFormMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting files..
        /// </summary>
        internal static string strExecuteFormDeleting {
            get {
                return ResourceManager.GetString("strExecuteFormDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done..
        /// </summary>
        internal static string strExecuteFormDone {
            get {
                return ResourceManager.GetString("strExecuteFormDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are downloading {0}/{1}.
        /// </summary>
        internal static string strExecuteFormDownloading {
            get {
                return ResourceManager.GetString("strExecuteFormDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are going to delete:.
        /// </summary>
        internal static string strExecuteFormGoDel {
            get {
                return ResourceManager.GetString("strExecuteFormGoDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are going to download:.
        /// </summary>
        internal static string strExecuteFormGoDownload {
            get {
                return ResourceManager.GetString("strExecuteFormGoDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will take follow changes:.
        /// </summary>
        internal static string strExecuteFormLabelText {
            get {
                return ResourceManager.GetString("strExecuteFormLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Cancel....
        /// </summary>
        internal static string strExecuteFormUserCancel {
            get {
                return ResourceManager.GetString("strExecuteFormUserCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for cancal....
        /// </summary>
        internal static string strExecuteFormWaiting {
            get {
                return ResourceManager.GetString("strExecuteFormWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Url:.
        /// </summary>
        internal static string strMainFormDownloadUrl {
            get {
                return ResourceManager.GetString("strMainFormDownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file first!.
        /// </summary>
        internal static string strMainFormOpenItem {
            get {
                return ResourceManager.GetString("strMainFormOpenItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download DB file....
        /// </summary>
        internal static string strSplashLabelDownloadDB {
            get {
                return ResourceManager.GetString("strSplashLabelDownloadDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download from {0} error, check the network..
        /// </summary>
        internal static string strSplashLabelDownloadError {
            get {
                return ResourceManager.GetString("strSplashLabelDownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load DB file.
        /// </summary>
        internal static string strSplashLabelLoadDB {
            get {
                return ResourceManager.GetString("strSplashLabelLoadDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading config file.
        /// </summary>
        internal static string strSplashLabelText {
            get {
                return ResourceManager.GetString("strSplashLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Software.
        /// </summary>
        internal static string strTypeFree {
            get {
                return ResourceManager.GetString("strTypeFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green Software.
        /// </summary>
        internal static string strTypeGreen {
            get {
                return ResourceManager.GetString("strTypeGreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Software.
        /// </summary>
        internal static string strTypeShare {
            get {
                return ResourceManager.GetString("strTypeShare", resourceCulture);
            }
        }
    }
}
